### ISSUE TITLE
Confused about how to declare connection

### ISSUE THREAD

**Issue by ziedHamdi** [graphql-compose/graphql-compose-connection#83]
There seems to be two distinct methods to create a connection from mongoose while adding custom sorting (https://graphql-compose.github.io/docs/plugins/plugin-connection.html and TC.mongooseResolvers.connection();

Short story: this code throws an exception (see below)

```
import {composeMongoose} from 'graphql-compose-mongoose';
import {Resolver, schemaComposer} from 'graphql-compose';
import {EntityGroupByVisitsView} from '../db'
import composeWithConnection from 'graphql-compose-connection';

const customizationOptions = {}; // left it empty for simplicity, described below
const EntityGroupByVisitsViewTC = composeMongoose(EntityGroupByVisitsView, customizationOptions)
const entityGroupByVisitsConnection = EntityGroupByVisitsViewTC.mongooseResolvers.connection();
const entityGroupByVisitsCount = EntityGroupByVisitsViewTC.mongooseResolvers.count();
const entityGroupByVisitsMany = EntityGroupByVisitsViewTC.mongooseResolvers.findMany();


schemaComposer.Query.addFields({
	entityGroupByVisitsById: EntityGroupByVisitsViewTC.mongooseResolvers.findById(),
	entityGroupByVisitsMany,
	entityGroupByVisitsCount,
	entityGroupByVisitsConnection,
});

composeWithConnection(EntityGroupByVisitsViewTC, {
		findResolver: entityGroupByVisitsMany,
		countResolver: entityGroupByVisitsCount,
		sort: {
			VISIT_COUNT_ID_ASC: {
				value: { totalVisits: -1, _id: -1 },
				// By these fields MUST be created COMPOUND UNIQUE index in database!
				cursorFields: ['totalVisits', '_id'],
				beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
					if (!rawQuery.totalVisits) rawQuery.totalVisits = {};
					if (!rawQuery._id) rawQuery._id = {};
					rawQuery.totalVisits.$gt = cursorData.totalVisits;
					rawQuery._id.$gt = cursorData._id;
				},
				afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
					if (!rawQuery.totalVisits) rawQuery.totalVisits = {};
					if (!rawQuery._id) rawQuery._id = {};
					rawQuery.totalVisits.$lt = cursorData.totalVisits;
					rawQuery._id.$lt = cursorData._id;
				},
			}
		}
	}
)

export default schemaComposer;
```

Here's the error: 

```
D:\Work\WeAllyBack\node_modules\graphql-compose-connection\lib\connection.js:38
        throw new Error(`Option 'opts.findManyResolver' must be a Resolver instance. Received ${graphql_compose_1.inspect(opts.findManyResolver)}`);
        ^

Error: Option 'opts.findManyResolver' must be a Resolver instance. Received undefined
    at Object.prepareConnectionResolver (D:\Work\WeAllyBack\node_modules\graphql-compose-connection\src\connection.ts:76:11)
    at composeWithConnection (D:\Work\WeAllyBack\node_modules\graphql-compose-connection\src\composeWithConnection.ts:25:20)
    at Object.<anonymous> (D:\Work\WeAllyBack\src\server\graphql\/entityGroupByVisits.js:20:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (D:\Work\WeAllyBack\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (D:\Work\WeAllyBack\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (D:\Work\WeAllyBack\src\server\graphql\/index.js:8:1)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Module._compile (D:\Work\WeAllyBack\node_modules\pirates\lib\index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Object.newLoader [as .js] (D:\Work\WeAllyBack\node_modules\pirates\lib\index.js:104:7)

```

**Comment by ziedHamdi** [comment]
Ok,

I solved it this way:

```
const SORT_VISIT_COUNT_ASC = {
	value: {totalVisits: -1, _id: -1},
	// By these fields MUST be created COMPOUND UNIQUE index in database!
	cursorFields: ['totalVisits', '_id'],
	beforeCursorQuery: (rawQuery, cursorData, resolveParams) => {
		if (!rawQuery.totalVisits) rawQuery.totalVisits = {};
		if (!rawQuery._id) rawQuery._id = {};
		rawQuery.totalVisits.$gt = cursorData.totalVisits;
		rawQuery._id.$gt = cursorData._id;
	},
	afterCursorQuery: (rawQuery, cursorData, resolveParams) => {
		if (!rawQuery.totalVisits) rawQuery.totalVisits = {};
		if (!rawQuery._id) rawQuery._id = {};
		rawQuery.totalVisits.$lt = cursorData.totalVisits;
		rawQuery._id.$lt = cursorData._id;
	},
};
const entityGroupByVisitsConnection = EntityGroupByVisitsViewTC.mongooseResolvers.connection({sort:{SORT_VISIT_COUNT_ASC}});

```
